### ISSUE TITLE
Keeps trying to connect

### ISSUE THREAD

**Issue by Edwin-Sun** [cetteup/bf2-auto-spectator#2]
I installed the latest stand-alone version. After starting the controller, it is starting BF2 with the correct username, it selects the multplayer server list and from there it keeps telling "connecting to server, re-connecting to server etc 
It is not connecting to the gameserver.

**Comment by cetteup** [comment]
What server are you trying to connect to? And does the game show any error messages?

I will build a new standalone version later today, since I made quite a few changes since the last release.

**Comment by Edwin-Sun** [comment]
Hi tired several servers. I tried our First-Legion server at ip: 5.79.100.144
Bf2 will start with the username and PW and I can see the mouse going to "Multiplayer" and refreshing the server browserlist but i stays there and my CMD screen keeps saying "re-connecting".

**Comment by cetteup** [comment]
The screenshot is good!

While I set up a new build, could you run the controller once with `--debug-log`?

And, just to make sure that's not an issue: I tried to send my own spectator to the server and it failed to join (Connection failed error). Can you manually join the servers you tried?

**Comment by Edwin-Sun** [comment]
I did what you said, putting --debug-log at the end but I dont see a log file

**Comment by Edwin-Sun** [comment]
I can log in normally whit the same account

**Comment by cetteup** [comment]
> I did what you said, putting --debug-log at the end but I dont see a log file

It does not log to a file, but should log to stdout (the console) like the logs seen in the screenshot. However, a quick look at the code tells me that not much more is actually logged when debug logging is enabled.

I just released [version 0.3.0](https://github.com/cetteup/bf2-auto-spectator/releases/tag/v0.3.0) which contains many small improvements, some directly related to how the spectator handles the server join. Please test if that works better. If it does not, please let me know if you see anything relevant in the logs when running with `--debug-log`.

**Comment by Edwin-Sun** [comment]
I see version 3 is only the "main" version amd not the complete "stand alone" version?

**Comment by cetteup** [comment]
It's just a name change. If you download and run the executable, it works just like the old versions did.

**Comment by Edwin-Sun** [comment]
I noticed the standalone version has a lot more folders

**Comment by cetteup** [comment]
As mentioned in the release note, it's just a change in how it is distributed. Instead of building an `.exe` with a bunch of files around it, it now distributed as a single `.exe` that contains everything.

All in all, it's just a pyinstaller option, about you which you find more details in the [pyinstaller documentation](https://pyinstaller.readthedocs.io/en/stable/usage.html).

**Comment by Edwin-Sun** [comment]
Sorry, but i don't see any exe file in your version 3

**Comment by Edwin-Sun** [comment]
Only two folders: pickle and src

**Comment by Edwin-Sun** [comment]
Used the new exe file "bf2-auto-spectator-0.3.0.exe with the same arguments as before bit i got the same problem. Bf2 will start and login to BFHQ but will not connect to gameserver. keeps re-connecting.

**Comment by cetteup** [comment]
Alright then, let's try and narrow this down.

1. What OS are you running?
2. Is your game set to English without any significant modifications to the locale file?
3. Have you changed anything else about the game/menu?
4. Have you checked the hints at the bottom of the readme? (100% scaling in Win10 etc.)
5. What GPU Brand are you using?

**Comment by Edwin-Sun** [comment]
1. Windows 10
2. English 
3. Bf2 video resolution 1600x900
4. Windows scaling is default at 100%
5. Nvidia

Verstuurd vanaf mijn iPhone

**Comment by Edwin-Sun** [comment]
I had a quick look into the pythoncode ( I am not familiar with programming ) and it looks like it is not going to "connect_tp_ip_button_present" in gameinstancemanager.py arounf line 354
I can see the mouse moving to BFHQ and Multiplayer but it is stuck in a loop. It will go back to BFHQ and Mulitplayer all the time

**Comment by Edwin-Sun** [comment]
Update:
When I change my windows grapic settings to 1600 x 900 and add the --game-re 900p argument, I can see the program opening the "connect to ip" button and fill in the ip and port. It comes back with the following error:

![BF2Spectator030-2](https://user-images.githubusercontent.com/70019223/119222077-d860b300-baf2-11eb-96a5-0a5a8717db77.jpg)

**Comment by cetteup** [comment]
According to the logs/the last screenshot, it is detecting an error message in game (connection lost).

Is that accurate? Does the game show an error message when trying to join now?

**Comment by Edwin-Sun** [comment]
I don’t see the game ( map ) start loading. It ends with connection lost and it loops again


Verstuurd vanaf mijn iPhone

**Comment by cetteup** [comment]
Since I had similar issues with that server, could you please try with a server I know usually works and is definitely online:

31.186.250.239 (Super@ S2)

**Comment by Edwin-Sun** [comment]
I will check yiur server in 10 minutes.

That connection problem has to do with PB enabled servers. I always have to login twice to connect to our PB enabled servers.
When I try a server without PB enabled ( just one of the BF2Hub un-ranked servers, it is connecting and loading the map.
The eror i get after laoding the map is:

![BF2Spectator030-4](https://user-images.githubusercontent.com/70019223/119225421-000c4700-bb04-11eb-8eeb-6b347573a31a.jpg)

**Comment by Edwin-Sun** [comment]
Using Super@ server:

![BF2Spectator030-5](https://user-images.githubusercontent.com/70019223/119225588-d3a4fa80-bb04-11eb-823a-f8a501aaa1e3.jpg)

**Comment by Edwin-Sun** [comment]
Update: I can connebt to PB enabled servers too ;)
But message about Spawn menu not vissible is still there :(

I noticed BF2 is tarted in windowed mode and it's not fully centered. I have 2 mm offset on the left and top of the BF2 window. Maybe it should start in Fullscreen mode?

**Comment by cetteup** [comment]
Ok, so some progress.

The game is intentionally started in windowed mode so you can see the console window.

But it now seems to not detect the spawn menu correctly. In order to be able to troubleshoot this, could you run it once with a working server and `--debug-screenshot` enabled? That will save all screenshots it takes into a folder as well as log all the OCR results.

Speaking of OCR, kindly let me know which version of Tesseract you have installed.

**Comment by Edwin-Sun** [comment]
The Tesserac version is v4.1.0.2019.0314 ( 64 bit )

I cant find any logfile?

**Comment by cetteup** [comment]
When running with `--debug-screenshot`, you should see a bunch of "OCR result:" log messages in the console.

I have been using version v5.0.0.20190623 lately, maybe try using that. You download the installer [here](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0.20190623.exe).

**Comment by Edwin-Sun** [comment]
Downloaded and installed v5.0.0.20190623 version but problem still the same.

When i open console with "~" i see this:

![IMG_7634](https://user-images.githubusercontent.com/70019223/119233477-9141e480-bb29-11eb-85db-c2c3994507d3.jpg)

**Comment by cetteup** [comment]
You mentioned before that you are using Windows 10, but the window frame in the screenshot looks like Windows 7.

Are you using some sort of skin/theme for Windows 10 that makes it look like Windows 7? If so, try resetting that to the default.

**Comment by Edwin-Sun** [comment]
No, it’s windows 10 without modifications 


Verstuurd vanaf mijn iPhone

**Comment by Edwin-Sun** [comment]
Change background from photo to default but still same problem.

**Comment by cetteup** [comment]
It's not the background that I suspect is causing the issue, it's the Windows theme. I suspect that the different theme is why the spectator keeps complaining about the window size as it shifts everything by a few pixels, which also messes with the OCR. This is what the window should look like on Windows 10:

![2021-05-22_19-23](https://user-images.githubusercontent.com/17167062/119235561-63619d80-bb33-11eb-85a2-4fd1eacabbd4.png)

What does the settings app say is your current theme? The default should look like this.

![2021-05-22_19-48](https://user-images.githubusercontent.com/17167062/119236265-b5f08900-bb36-11eb-90a4-e1d797381d77.png)

Also, please double check your exact version of Windows via "About your PC".

**Comment by Edwin-Sun** [comment]
This is my background / theme:

![IMG_7635](https://user-images.githubusercontent.com/70019223/119242114-bfd8b300-bb5b-11eb-81e4-cc2caa5f8be9.jpg)

![IMG_7636](https://user-images.githubusercontent.com/70019223/119242116-c535fd80-bb5b-11eb-9808-ff6965f7493f.jpg)

**Comment by cetteup** [comment]
The windows theme and background are two different things. Please check your theme settings instead of your background settings. I am not sure what "Theme" would be in NL, but it should the 4th option in the menu.

![2021-05-23_10-14](https://user-images.githubusercontent.com/17167062/119253086-c2fd8e80-bbaf-11eb-9345-04c2473369e6.png)

**Comment by Edwin-Sun** [comment]
I changed theme to Windows 10

![image](https://user-images.githubusercontent.com/70019223/119255462-3efdd380-bbbc-11eb-9193-bb4d18bca173.jpeg)

**Comment by Edwin-Sun** [comment]
Problem is still there, player is not spawning

**Comment by cetteup** [comment]
Which theme were you using before? Please try with the "Windows" theme, which is the default.

Also, are you running BF2 with any compatibility options enabled?

**Comment by Edwin-Sun** [comment]
No change :(
Same problem at my laptop.

**Comment by cetteup** [comment]
Hm. There's not much I can do, unfortunately. I am pretty sure that the non-standard Windows 10 theme results in a different window size. The spectator logs something about an "incorrect window size" several times, which it should never do when starting the game itself. And due to the different window size, some of OCR attempts or game state detections in general fail.

**Comment by Edwin-Sun** [comment]
Windows display settings are 1600 x 900
Theme is "Windows"
I see the same offset left and top at your example picture, so i guess thats okay.
It keeps on drawing the hud and the hud comes up.
But the hud is not showing the complete map picture!

![IMG_7642](https://user-images.githubusercontent.com/70019223/119267694-01b33900-bbf0-11eb-859d-035a7802e34a.jpg)

Maybe the OCR likes to see full Karkand map picture in the HUD?

**Comment by cetteup** [comment]
Which version of Windows 10 are you using?

And no, it has nothing to do with the map (it never looks at that). The issues are probably just caused by the different window size, which moves everything my a few pixels and thus messes everything up.

**Comment by Edwin-Sun** [comment]
![WindowsVersion](https://user-images.githubusercontent.com/70019223/119268406-1513d380-bbf3-11eb-8a86-49a25544450f.jpg)

**Comment by Edwin-Sun** [comment]
I chabged resolution from 900p to 720p.
I get an error message at the console:

![Uploading IMG_7643.jpg…]()

**Comment by cetteup** [comment]
It will not work unless you manage to start the game in a normal Windows 10 window. The resolution does not matter.

If you have something like "Classic shell" installed, try removing it. If you are running BF2 in compatibility mode, try without it.

But other than that, I'm afraid I really cannot help you.
